"""HTTP fixtures for paid APIs: identifiers, plan errors, and durable evidence jobs."""

from __future__ import annotations

import json
from urllib.parse import urlsplit

import httpx
import pytest

from research_engine.providers.base import Capability, ErrorKind, ProviderError
from research_engine.providers.scholar.consensus_api import ConsensusAPIProvider
from research_engine.providers.scholar.elicit_api import ElicitAPIProvider

SESSION_ID = "5ad08bfb-cbe0-4911-a8c3-309760d33029"
EXPORT_URL = "https://exports.example.org/papers.csv?signature=fixture"


class Context:
    def __init__(self, provider, handler, *, credentials=None, options=None):
        self.provider = provider
        self.account_id = 7
        self.credentials = {"api_key": "fixture-key"} if credentials is None else credentials
        self.options = options or {}
        self.requests = []
        self.validated = []

        def capture(request):
            self.requests.append(request)
            return handler(request)

        self.client = httpx.AsyncClient(transport=httpx.MockTransport(capture))

    async def request(self, method, url, **kwargs):
        return await self.client.request(method, url, **kwargs)

    async def validate_url(self, url):
        self.validated.append(url)
        parsed = urlsplit(url)
        if parsed.scheme != "https" or parsed.hostname in {"localhost", "127.0.0.1", "169.254.169.254"}:
            raise ProviderError(ErrorKind.BAD_REQUEST, "Unsafe export URL")


@pytest.fixture
async def context():
    contexts = []

    def make(provider, payload=None, *, status=200, handler=None, **kwargs):
        ctx = Context(provider, handler or (lambda _: httpx.Response(status, json=payload)), **kwargs)
        contexts.append(ctx)
        return ctx

    yield make
    for ctx in contexts:
        await ctx.client.aclose()


async def test_consensus_current_get_contract_and_free_plan_identifiers(context):
    ctx = context("consensus_api", {"results": [{"paper_id": "paper-123", "title": "Trial paper",
        "publish_year": 2024, "abstract": "Original abstract", "key_takeaway": "Generated conclusion",
        "url": "https://consensus.app/papers/paper-123"}], "page": 0, "next_page": 1, "is_end": False})
    result = await ConsensusAPIProvider().call(Capability.PAPER_SEARCH, {"query": "trial", "limit": 3}, ctx)
    request = ctx.requests[0]
    assert request.method == "GET"
    assert request.url.path == "/v1/search"
    assert request.headers["x-api-key"] == "fixture-key"
    assert request.url.params["page_size"] == "3"
    hit = result.hits[0]
    assert hit.ids == {"consensus": "paper-123"}
    assert hit.snippet == "Original abstract"
    assert hit.year == 2024 and hit.account == 7 and hit.rank == 1
    assert result.cursor == "1" and result.document is None


async def test_consensus_never_uses_generated_takeaway_as_abstract(context):
    ctx = context("consensus_api", {"results": [{"title": "Paper", "key_takeaway": "Claim generated by AI"}]})
    result = await ConsensusAPIProvider().call(Capability.PAPER_SEARCH, {"query": "x"}, ctx)
    assert result.hits[0].snippet is None
    assert result.hits[0].ids == {}


async def test_consensus_normalizes_only_supplied_doi(context):
    ctx = context("consensus_api", {"results": [{"title": "Paper", "doi": "https://doi.org/10.1234/ABC"}]})
    result = await ConsensusAPIProvider().call(Capability.PAPER_SEARCH, {"query": "x"}, ctx)
    assert result.hits[0].ids == {"doi": "10.1234/abc"}
    assert result.hits[0].url == "https://doi.org/10.1234/abc"


@pytest.mark.parametrize("provider", [ConsensusAPIProvider(), ElicitAPIProvider()])
async def test_missing_key_is_authentication_error(context, provider):
    ctx = context(provider.name, {}, credentials={})
    with pytest.raises(ProviderError) as exc:
        await provider.call(Capability.PAPER_SEARCH, {"query": "paper"}, ctx)
    assert exc.value.kind == ErrorKind.AUTH
    assert not ctx.requests


@pytest.mark.parametrize("status,code,kind", [(403, "api_access_denied", ErrorKind.PLAN),
    (401, "invalid_api_key", ErrorKind.AUTH), (402, "insufficient_quota", ErrorKind.EXHAUSTED),
    (429, "rate_limited", ErrorKind.RATE_LIMITED), (500, "internal_error", ErrorKind.TRANSIENT)])
async def test_elicit_error_classification(context, status, code, kind):
    ctx = context("elicit_api", {"error": {"code": code, "message": "fixture"}}, status=status)
    with pytest.raises(ProviderError) as exc:
        await ElicitAPIProvider().call(Capability.PAPER_SEARCH, {"query": "x"}, ctx)
    assert exc.value.kind == kind


async def test_elicit_search_preserves_rank_and_paper_identities(context):
    ctx = context("elicit_api", {"papers": [{"elicitId": "e2", "title": "Second", "year": 2023,
        "doi": "10.1234/B", "abstract": "Source abstract", "authors": [{"name": "A. Author"}]},
        {"elicitId": "e1", "title": "First", "pmid": "123456", "urls": ["https://example.org/paper"]}],
        "warnings": ["fixture_warning"]}, options={"corpus": "elicit"})
    result = await ElicitAPIProvider().call(Capability.PAPER_SEARCH, {"query": "effects", "limit": 4}, ctx)
    request = ctx.requests[0]
    assert request.method == "POST" and request.url.path == "/api/v2/search/papers"
    assert request.headers["authorization"] == "Bearer fixture-key"
    assert json.loads(request.content) == {"query": "effects", "maxResults": 4, "corpus": "elicit"}
    assert [hit.rank for hit in result.hits] == [1, 2]
    assert result.hits[0].ids == {"doi": "10.1234/b", "elicit": "e2"}
    assert result.hits[1].ids == {"pmid": "123456", "elicit": "e1"}
    assert result.hits[0].authors == ["A. Author"]
    assert result.raw["warnings"] == ["fixture_warning"]


@pytest.mark.parametrize("cap,kind", [(Capability.DEEP_LITERATURE_SEARCH, "reports"),
                                      (Capability.SYSTEMATIC_REVIEW, "systematic-reviews")])
async def test_elicit_creates_private_jobs_and_restart_safe_reference(context, cap, kind):
    ctx = context("elicit_api", {"sessionId": SESSION_ID, "url": "http://127.0.0.1/ignored",
                                "links": {"self": "http://127.0.0.1/ignored"}})
    ref = await ElicitAPIProvider().start(cap, {"question": "What works?", "max_extract_papers": 500}, ctx)
    assert json.loads(ref) == {"kind": kind, "session_id": SESSION_ID}
    request = ctx.requests[0]
    assert request.url.path == f"/api/v2/sessions/{kind}"
    payload = json.loads(request.content)
    assert payload["isPublic"] is False
    if kind == "reports":
        assert payload["maxExtractPapers"] == 80
    else:
        assert payload["generateReport"] is False
    assert "fixture-key" not in ref and "127.0.0.1" not in ref


def job_ref(kind="reports"):
    return json.dumps({"kind": kind, "session_id": SESSION_ID})


async def test_elicit_paused_quota_remains_recoverable(context):
    ctx = context("elicit_api", {"sessionId": SESSION_ID, "status": "pausedForInsufficientQuota",
                                "links": {"resume": "http://127.0.0.1/ignored"}})
    update = await ElicitAPIProvider().poll(ctx, job_ref())
    assert update.status == "running" and update.poll_after_s == 60
    assert "insufficient quota" in update.error
    assert len(ctx.requests) == 1


async def test_elicit_deep_goal_and_review_criteria_inputs(context):
    ctx = context("elicit_api", {"sessionId": SESSION_ID})
    await ElicitAPIProvider().start(Capability.DEEP_LITERATURE_SEARCH, {"goal": "Find evidence"}, ctx)
    assert json.loads(ctx.requests[0].content)["researchQuestion"] == "Find evidence"
    await ElicitAPIProvider().start(Capability.SYSTEMATIC_REVIEW,
                                  {"question": "What works?", "criteria": ["Randomized trials", "Adults"]}, ctx)
    assert json.loads(ctx.requests[1].content)["protocolDetails"] == "Randomized trials\nAdults"


async def test_elicit_creation_timeout_is_ambiguous(context):
    def handler(request):
        raise httpx.ReadTimeout("fixture timeout", request=request)

    ctx = context("elicit_api", handler=handler)
    with pytest.raises(ProviderError) as exc:
        await ElicitAPIProvider().start(Capability.DEEP_LITERATURE_SEARCH, {"goal": "Find evidence"}, ctx)
    assert exc.value.kind == ErrorKind.TRANSIENT
    assert exc.value.ambiguous_start is True


async def test_elicit_opt_in_resume_uses_known_host(context):
    ctx = context("elicit_api", {"sessionId": SESSION_ID, "status": "pausedForInsufficientQuota",
        "links": {"resume": "http://127.0.0.1/ignored"}}, options={"resume_paused_jobs": True})
    update = await ElicitAPIProvider().poll(ctx, job_ref())
    assert update.status == "running"
    assert ctx.requests[1].method == "POST"
    assert str(ctx.requests[1].url) == f"https://elicit.com/api/v2/sessions/{SESSION_ID}/resume"


async def test_elicit_unsuccessful_resume_preserves_paused_job(context):
    def handler(request):
        if request.method == "POST":
            return httpx.Response(402, json={"error": {"code": "insufficient_quota", "message": "Still paused"}})
        return httpx.Response(200, json={"status": "pausedForInsufficientQuota"})

    ctx = context("elicit_api", handler=handler, options={"resume_paused_jobs": True})
    update = await ElicitAPIProvider().poll(ctx, job_ref())
    assert update.status == "running" and update.poll_after_s == 60
    assert len(ctx.requests) == 2


@pytest.mark.parametrize("status,expected", [("processing", "running"), ("unknown", "running"), ("failed", "failed")])
async def test_elicit_polling_states(context, status, expected):
    ctx = context("elicit_api", {"status": status})
    assert (await ElicitAPIProvider().poll(ctx, job_ref())).status == expected


async def test_elicit_completed_report_downloads_papers_never_narrative(context):
    def handler(request):
        if request.url.host == "elicit.com":
            return httpx.Response(200, json={"status": "completed", "risUrl": EXPORT_URL,
                "exportsStatus": "ready", "result": {"reportBody": "Generated findings", "summary": "Generated"}})
        assert "authorization" not in request.headers
        return httpx.Response(200, text="TY  - JOUR\nTI  - Source paper\nDO  - 10.1234/ABC\nAU  - An Author\nPY  - 2021\nAB  - Original abstract\nER  -\n")

    ctx = context("elicit_api", handler=handler)
    # A new provider instance has no in-memory state from the job creation process.
    update = await ElicitAPIProvider().poll(ctx, job_ref())
    assert update.status == "completed" and update.result.document is None
    assert ctx.validated == [EXPORT_URL]
    hit = update.result.hits[0]
    assert hit.ids == {"doi": "10.1234/abc"} and hit.snippet == "Original abstract"
    assert hit.raw["session_id"] == SESSION_ID and hit.rank == 1
    assert "Generated findings" not in update.result.model_dump_json()


async def test_elicit_completed_review_retains_csv_ranking_and_provenance(context):
    def handler(request):
        if request.url.host == "elicit.com":
            return httpx.Response(200, json={"status": "completed", "exportsStatus": "ready", "data": {
                "extract": {"csv": EXPORT_URL}, "search": {"csv": "https://exports.example.org/search.csv"},
                "report": {"result": {"summary": "Generated"}}}})
        assert "authorization" not in request.headers
        return httpx.Response(200, text='Title,DOI,Year,Abstract,Generated conclusion\nSource A,10.1234/A,2020,Original A,Generated A\nSource B,10.1234/B,2021,Original B,Generated B\n')

    ctx = context("elicit_api", handler=handler)
    update = await ElicitAPIProvider().poll(ctx, job_ref("systematic-reviews"))
    assert update.status == "completed"
    assert [hit.rank for hit in update.result.hits] == [1, 2]
    assert [hit.snippet for hit in update.result.hits] == ["Original A", "Original B"]
    assert update.result.raw["export_stage"] == "extract"
    assert update.result.document is None and ctx.validated == [EXPORT_URL]


@pytest.mark.parametrize("exports_status,expected", [("generating", "running"), ("unavailable", "failed")])
async def test_elicit_unavailable_exports_do_not_claim_evidence(context, exports_status, expected):
    ctx = context("elicit_api", {"status": "completed", "exportsStatus": exports_status,
        "result": {"reportBody": "Generated narrative"}})
    update = await ElicitAPIProvider().poll(ctx, job_ref())
    assert update.status == expected and update.result is None


async def test_elicit_blocks_private_export_url(context):
    ctx = context("elicit_api", {"status": "completed", "risUrl": "http://169.254.169.254/latest/meta-data"})
    with pytest.raises(ProviderError):
        await ElicitAPIProvider().poll(ctx, job_ref())
    assert len(ctx.requests) == 1


@pytest.mark.parametrize("ref", ['{"kind":"../evil","session_id":"x"}',
                                 '{"kind":"reports","session_id":"http://127.0.0.1"}', "not json"])
async def test_elicit_rejects_unsafe_job_reference(context, ref):
    ctx = context("elicit_api", {})
    with pytest.raises(ProviderError) as exc:
        await ElicitAPIProvider().poll(ctx, ref)
    assert exc.value.kind == ErrorKind.BAD_REQUEST and not ctx.requests


async def test_elicit_invalid_export_is_not_a_success(context):
    def handler(request):
        if request.url.host == "elicit.com":
            return httpx.Response(200, json={"status": "completed", "data": {"search": {"csv": EXPORT_URL}}})
        return httpx.Response(200, text="<html>Log in to see this report</html>")

    ctx = context("elicit_api", handler=handler)
    with pytest.raises(ProviderError) as exc:
        await ElicitAPIProvider().poll(ctx, job_ref("systematic-reviews"))
    assert exc.value.kind == ErrorKind.TRANSIENT
